name: SUH-PROJECT-BE-CICD

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Java 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle Wrapper 실행권한 부여
        run: chmod +x gradlew

      - name: application-suh.yml 생성
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_SUH_YML }}" > ./src/main/resources/application-suh.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test -Dspring.profiles.active=suh

      - name: Docker 빌드환경 설정
        uses: docker/setup-buildx-action@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SUH_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SUH_DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.SUH_DOCKERHUB_USERNAME }}/freemates-back-container:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SUH_SERVER_HOST }}
          username: ${{ secrets.SUH_SERVER_USER }}
          password: ${{ secrets.SUH_SERVER_PASSWORD }}
          port: 2022
          script: |
            set -e
            
            echo "환경변수 설정.."
            export PATH=$PATH:/usr/local/bin
            export PW=${{ secrets.SUH_SERVER_PASSWORD }}
            BRANCH=${{ github.ref_name }}
            PORT=8080
            CONTAINER_NAME="freemates-back"
            
            if [ "$BRANCH" == "main" ]; then
              PORT=8092
            elif [ "$BRANCH" == "test" ]; then
              CONTAINER_NAME="freemates-back-test"
              PORT=8093
            fi
            
            echo "브랜치: $BRANCH"
            echo "컨테이너 이름: $CONTAINER_NAME"
            echo "포트: $PORT"
            
            echo "도커 이미지 풀 : ${{ secrets.SUH_DOCKERHUB_USERNAME }}/freemates-back-container:${BRANCH}"
            echo $PW | sudo -S docker pull ${{ secrets.SUH_DOCKERHUB_USERNAME }}/freemates-back-container:${BRANCH}
            
            echo "컨테이너 $CONTAINER_NAME 존재 여부 확인 중..."
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}\$"; then
              echo "컨테이너 $CONTAINER_NAME 이(가) 존재합니다. 중지 및 삭제 중..."
              echo $PW | sudo -S docker rm -f $CONTAINER_NAME
              echo "컨테이너 $CONTAINER_NAME 이(가) 삭제되었습니다."
            else
              echo "존재하는 컨테이너 $CONTAINER_NAME 이(가) 없습니다."
            fi
            
            echo "새로운 컨테이너 $CONTAINER_NAME 실행 중..."
            echo $PW | sudo -S docker run -d -p ${PORT}:8080 --name $CONTAINER_NAME \
              -e TZ=Asia/Seoul \
              -e "SPRING_PROFILES_ACTIVE=suh" \
              -v /etc/localtime:/etc/localtime:ro \
              -v /volume1/projects/freemates:/mnt/freemates \
              ${{ secrets.SUH_DOCKERHUB_USERNAME }}/freemates-back-container:${BRANCH}
            
            echo "배포가 성공적으로 완료되었습니다."